Checkpoint:Mathematics for Data Science

Data Analysis and Matrix Operations

In [ ]:
import numpy as np
import statistics as st


In [ ]:
matrixA = np.array([[2,3],[1,7],[8,9]])
matrixB = np.array([[10,12],[9,11],[2,3]])
print(type(matrixA))
print(type(matrixB))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [ ]:
print(np.mean(matrixA))
print(np.mean(matrixB))

5.0
7.833333333333333


In [ ]:
np.median(matrixA)


5.0

In [ ]:
np.median(matrixB)

9.5

In [ ]:
from scipy import stats

In [ ]:

print(stats.mode(matrixA))

ModeResult(mode=array([1, 3]), count=array([1, 1]))


In [ ]:
print(stats.mode(matrixB))

ModeResult(mode=array([2, 3]), count=array([1, 1]))


In [ ]:
flattened_matrixA = matrixA.flatten()
print(st.mode(flattened_matrixA))


2


In [ ]:
flattened_matrixB = matrixB.flatten()
print(flattened_matrixB)
print(st.mode(flattened_matrixB))

[10 12  9 11  2  3]
10


In [ ]:
print(matrixA + matrixB)


[[12 15]
 [10 18]
 [10 12]]


In [ ]:
print(matrixA - matrixB)

[[-8 -9]
 [-8 -4]
 [ 6  6]]


In [ ]:
print(np.transpose(matrixA))

[[2 1 8]
 [3 7 9]]


In [ ]:
print(np.transpose(matrixB))

[[10  9  2]
 [12 11  3]]


In [ ]:
k = 12
print(k*matrixA)

[[ 24  36]
 [ 12  84]
 [ 96 108]]


In [ ]:
x = 10
print(x*matrixB)

[[100 120]
 [ 90 110]
 [ 20  30]]


Matrices play a crucial role in building recommendation systems, widely used in e-commerce, streaming services, and social media platforms.

In [ ]:
dataset = [95,105,112,116,133,148,155,156,231]

In [ ]:
st.stdev(dataset)

41.04266073246227

In [ ]:
st.variance(dataset)

1684.5

In [ ]:
st.mean(dataset)

139